### ISSUE TITLE
你好，我想对yolov5s上训练的模型进行稀疏训练，提示缺少DetectionModel

### ISSUE THREAD

**Issue by zy597337447** [midasklr/yolov5prune#111]
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'D:\\Papers_models\\yolov5prune\\models\\yolo.py'>

**Comment by zy597337447** [comment]
版本问题，已经解决

**Comment by aminey555** [comment]
你好，请问你怎么解决的？
