### ISSUE TITLE
稀疏训练MAP为零

### ISSUE THREAD

**Issue by juechenzp** [midasklr/yolov5prune#18]
感谢你的开源代码，我首先使用train.py训练，map=0.9； 然后我使用train_sparsity.py训练，sr=0.0001,发现map=0，当我想验证以下您的代码时，我又将sr=0,结果map=0.1；理论上sr=0时，train_spartrain_sparsity.pysity.py的结果应该等同于train.py，但是差距非常大。可以提供以下帮助吗，代码是否有问题呢。

**Comment by midasklr** [comment]
能不能贴一下tensorboard的map和bn hist图

**Comment by juechenzp** [comment]
抱歉，未及时看到消息，我之前是用的100张图片做的训练，然后也用这100张做测试，map=0，说明不收敛；我现在换成了1700张图片做训练，map比原始会低一点，可能跟训练集数量有关系。但是我依然想不通当我把sr设置为零时稀疏训练map=0，sr=0时应该更原始的train.py结果一致才对啊。 我不知道怎么显示hist图，我没有看到这个相关操作，可以方便指点一下吗，感谢。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "midasklr/yolov5prune"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [midasklr/yolov5prune] 稀疏训练MAP为零 (#18)





 
能不能贴一下tensorboard的map和bn hist图

**Comment by juechenzp** [comment]
你好，我发现在大数据集上map指标略低一点，可以接受，并且稀疏训练剪枝后模型体积变得更小。使用你提供的代码进行detect.py推理时，使用稀疏剪枝确实比不使用要快很多。但是我发现一个问题，我使用你提供的代码稀疏剪枝时，推理速度仍然低于从u版yolov5.0下载的代码，并且使用你的代码不进行稀疏剪枝时会比u版yolov5.0慢一倍，无论是gpu还是cpu。并且我还对比了您的代码和yolo3.1的速度，仍然低于yolov3.1，无论是否使用剪枝。可以帮助我解决这个问题吗，我觉得这是个很值得探讨的问题。
