### ISSUE TITLE
有关稀疏训练的问题

### ISSUE THREAD

**Issue by OpenCDR** [midasklr/yolov5prune#39]
作者您好，首先感谢一下您的代码。我在使用`python train_sparsity.py --st --sr 0.1 --weights yolov5s.pt --adam --epochs 100 --batch_size 180`调用稀疏训练的代码时，发现bn层的权重变化很小，这种情况应该如何解决呢？
![屏幕截图 2021-09-21 162253](https://user-images.githubusercontent.com/61880751/134139874-d1b996ef-16f5-45ed-8ad2-b7a263adc309.png)

**Comment by Yonglild** [comment]
同样地，我用coco128训练，调用稀疏训练的代码，bn层的分布没有趋向于0。请教一下作者，应该如何解决?

**Comment by Yonglild** [comment]
同样的。我用coco128训练。调用稀疏训练的代码，bn层的分布没有趋向于0。`python train_sparsity.py --st --sr 0.0001 --weights yolov5s.pt --adam --epochs 100`。请教一下作者，该如何解决呢？

**Comment by zimuyuan** [comment]
我用 coco128训练也遇到同样的问题的，bn_bias/hist 可以趋于 0，bn_weights/hist 还是正态分布，稀释训练没起到效果。
![image](https://user-images.githubusercontent.com/40883979/137608923-e7d00049-bb96-448d-a575-afa000b29c2d.png)

**Comment by Hazel-Xiang** [comment]
不好意思，小白想问我呢，这个bn_bias的图是在tensorboard上看吗？

**Comment by czzerone** [comment]
你好，我想问一下你这个问题解决了吗

**Comment by OpenCDR** [comment]
> 

已经解决了，是epochs设定的过大的原因

**Comment by silenterA2** [comment]
我也遇到了类似的问题，我已经把sr设为0.5了，但还是向0移动的很慢，请问您把epochs调小就解决了吗？可是epochs小的话效果不应该停留在前几层吗？请问您最后sr设置的大概是多少。

**Comment by OpenCDR** [comment]
不好意思，时间有点长我记不太清了。
sr调到0.05 epochs调到16

**Comment by puyiwen** [comment]
> 我也遇到了类似的问题，我已经把sr设为0.5了，但还是向0移动的很慢，请问您把epochs调小就解决了吗？可是epochs小的话效果不应该停留在前几层吗？请问您最后sr设置的大概是多少。

你好，你有出现过稀疏训练后的精度比原始精度低很多的问题吗？我已经把s参数设定为1e-5了。。。

**Comment by jzqqwq** [comment]
> > 我也遇到了类似的问题，我已经把sr设为0.5了，但还是向0移动的很慢，请问您把epochs调小就解决了吗？可是epochs小的话效果不应该停留在前几层吗？请问您最后sr设置的大概是多少。
> 
> 你好，你有出现过稀疏训练后的精度比原始精度低很多的问题吗？我已经把s参数设定为1e-5了。。。

你好，请问你解决这个问题了吗，我是用coco128数据训练的，系数前mAP70左右，稀疏后成了20左右了

**Comment by puyiwen** [comment]
> > > 我也遇到了类似的问题，我已经把sr设为0.5了，但还是向0移动的很慢，请问您把epochs调小就解决了吗？可是epochs小的话效果不应该停留在前几层吗？请问您最后sr设置的大概是多少。
> > 
> > 
> > 你好，你有出现过稀疏训练后的精度比原始精度低很多的问题吗？我已经把s参数设定为1e-5了。。。
> 
> 你好，请问你解决这个问题了吗，我是用coco128数据训练的，系数前mAP70左右，稀疏后成了20左右了

我不是做目标检测任务的，我做单目深度估计回归任务的。我把s参数又缩小了，然后好了

**Comment by jzqqwq** [comment]
> > > > 我也遇到了类似的问题，我已经把sr设为0.5了，但还是向0移动的很慢，请问您把epochs调小就解决了吗？可是epochs小的话效果不应该停留在前几层吗？请问您最后sr设置的大概是多少。
> > > 
> > > 
> > > 你好，你有出现过稀疏训练后的精度比原始精度低很多的问题吗？我已经把s参数设定为1e-5了。。。
> > 
> > 
> > 你好，请问你解决这个问题了吗，我是用coco128数据训练的，系数前mAP70左右，稀疏后成了20左右了
> 
> 我不是做目标检测任务的，我做单目深度估计回归任务的。我把s参数又缩小了，然后好了

请问s参数大概设置成多少精度会差不多呢，我是小白，刚开始学习深度学习

**Comment by gyf0951** [comment]
请问你们在使用train.py进行正常训练的时候怎么把bn_weights/hist这个直方图画出来啊？我看作者的train.py中好像没有画这个图的
