### ISSUE TITLE
How do I modify the default activation function silu to match your sparse, pruned, etc. files?

### ISSUE THREAD

**Issue by ilem777** [midasklr/yolov5prune#61]
Hello author @midasklr , I would like to modify the default silu activation function of yolov5 to become frelu to get better performance. I noticed that the Conv() module needs to replace silu with frelu here.
https://github.com/midasklr/yolov5prune/blob/b91f8a4f99667c2cd314db49be4b703d4c20f73d/models/common.py#L39 to
`self.act = FReLU(c2) if act is True else (act if isinstance(act, nn.Module) else nn.Identity())`
So, I would like to ask what else I need to modify in the other files? to match your sparse training script, pruning script, and recovery training script.

**Comment by midasklr** [comment]
just modify as you do,  you can still use the pruning script after you change the activation function.

**Comment by ilem777** [comment]
@midasklr Got it. Thank you.
