### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'cfg'

### ISSUE THREAD

**Issue by ouening** [midasklr/yolov5prune#69]
运行剪枝的时候报如题所示错误：
<pre>test before prune ... 
Traceback (most recent call last):
  File &quot;/yolov5prune-6.0/prune.py&quot;, line 805, in &lt;module&gt;
    main(opt)
  File &quot;/yolov5prune-6.0/prune.py&quot;, line 775, in main
    run(**vars(opt))
  File &quot;/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py&quot;, line 28, in decorate_context
    return func(*args, **kwargs)
TypeError: run() got an unexpected keyword argument &apos;cfg&apos;
</pre>

**Comment by ouening** [comment]
已经解决

**Comment by msddmzy** [comment]
> 运行剪枝的时候报如题所示错误：
> 
> test before prune ... 
> Traceback (most recent call last):
>   File "/yolov5prune-6.0/prune.py", line 805, in <module>
>     main(opt)
>   File "/yolov5prune-6.0/prune.py", line 775, in main
>     run(**vars(opt))
>   File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
> TypeError: run() got an unexpected keyword argument 'cfg'

师兄，请问您这个问题是怎么解决的呀？

**Comment by songguanxian** [comment]
> 已经解决

请问是如何解决的
