### ISSUE TITLE
AssertionError: Current remaining channel must greater than 0!!! please set prune percent to lower thesh, or you can retrain a more sparse model...

### ISSUE THREAD

**Issue by ouening** [midasklr/yolov5prune#70]
稀疏训练之后进行剪枝一直提示这个错误，已经尝试过很多稀疏模型了，sr从0.0005到0.05都试过了，s,m模型都尝试过，都报这个错误，用的自己的数据集，请问该怎么解决呢？看bn weight的趋势有向0偏移，但没有作者截图显示的那么明显

**Comment by JimmyW-11** [comment]
> 稀疏训练之后进行剪枝一直提示这个错误，已经尝试过很多稀疏模型了，sr从0.0005到0.05都试过了，s,m模型都尝试过，都报这个错误，用的自己的数据集，请问该怎么解决呢？看bn weight的趋势有向0偏移，但没有作者截图显示的那么明显

我也出现了这个问题，尝试过很多的稀疏模型，BN的分布也是可以的，但剪枝率超过0.2就会有这个问题，请问您现在解决了吗？

**Comment by ouening** [comment]
我是通过继续增大sr解决的，具体的忘了

**Comment by Zhengzhiyang0000** [comment]
你好请问你们是怎样解决这个问题啊
