### ISSUE TITLE
优化器用SGD不能稀疏训练？

### ISSUE THREAD

**Issue by damon-he** [midasklr/yolov5prune#80]
我把优化器从adam换成sgd，稀疏训练后发现BN层的gamm系数没有变化，还是呈正太分布。这是为啥呢？

**Comment by damon-he** [comment]
学习率也要跟着调整才行

**Comment by xinxin12345** [comment]
> ```
> 我把优化器从adam换成sgd，稀疏训练后发现BN层的gamm系数没有变化，还是呈正太分布。这是为啥呢？
> ```

您好，请问这个解决了吗，为什么不同优化器会影响稀疏训练？
