### ISSUE TITLE
prune.py报错

### ISSUE THREAD

**Issue by changchencjx** [midasklr/yolov5prune#94]
您好，我在稀疏训练完之后运行prune.py，出现如下错误
Traceback (most recent call last):
  
File "prune.py", line 805, in <module>
    
test_prune(opt.data,
  
File "prune.py", line 385, in test_prune
    
highest_thre = min(highest_thre)

ValueError: min() arg is an empty sequence
然后发现上面的`if isinstance(layer, nn.BatchNorm2d):`这一句判断一直是false，也就是貌似layer里的bn都不见了？
这是我稀疏训练的bn权重分布
![QQ截图20220525143452](https://user-images.githubusercontent.com/61176443/170196191-45a8665a-9636-4088-9261-73b2c8d56f52.png)
应该也是正常的，所以不清楚是出了什么问题，求解答！

**Comment by Dimitri666** [comment]
你好，请问你现在解决这个问题了吗？
